# vim: set ts=2 sw=2 tw=0 fo=cnqoj
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - go_first_class

dockers:
  - image_templates:
      - &amd64_image "{{ .Env.IMAGE_ROOT }}:{{ .Version }}-amd64"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --provenance=false
  - image_templates:
      - &arm64_image "{{ .Env.IMAGE_ROOT }}:{{ .Version }}-arm64"
    goos: linux
    goarch: arm64
    goarm: 8
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --provenance=false

docker_manifests:
  - name_template: "{{ .Env.IMAGE_ROOT }}:{{ .Version }}"
    image_templates:
      - *amd64_image
      - *arm64_image
  - name_template: "{{ .Env.IMAGE_ROOT }}:latest"
    image_templates:
      - *amd64_image
      - *arm64_image

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  disable: true
